# Generated by Django 5.0.3 on 2024-03-29 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_descripiton_review_descripition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descripition',
            new_name='description',
        ),
    ]
